### PR TITLE
Antidifferentiate

### PR DESCRIPTION
**Pull request by bmxam**
Implementation of `MultivariatePolynomials.antidifferentiate` function. I am more familiar with `TypedPolynomials` than with `DynamicPolynomials` so implementations improvements and/or comments are welcome. I did not find tests on the `diff` function so I did not provide tests for `antidifferentiate`. However, tests will be added in `MultivariatePolynomials.jl` (we first need to merge this PR before I can propose the tests).

### CODE REVIEW

**Comment by blegat** [comment]
Actually, you can add tests in MultivariatePolynomals now as we are doing a breaking release: https://github.com/JuliaAlgebra/MultivariatePolynomials.jl/issues/250
You can change the branches in `.github/workflow/ci.yml` so that ci works on the PR.

**Comment by bmxam** [comment]
> Actually, you can add tests in MultivariatePolynomals now as we are doing a breaking release: [JuliaAlgebra/MultivariatePolynomials.jl#250](https://github.com/JuliaAlgebra/MultivariatePolynomials.jl/issues/250) You can change the branches in `.github/workflow/ci.yml` so that ci works on the PR.

Do you mean changing `MultivariatePolynomials.jl/.github/workflow/ci.yml` so that `MultivariatePolynomials.jl` ci works on the present PR?

**Comment by blegat** [comment]
Yes, see what was done in https://github.com/JuliaAlgebra/MultivariatePolynomials.jl/pull/255/files for instance

**Comment by blegat** [comment]
You can see an example in https://github.com/JuliaAlgebra/DynamicPolynomials.jl/pull/135, https://github.com/JuliaAlgebra/MultivariatePolynomials.jl/pull/268

**Comment by bmxam** [comment]
Thanks, I'll take a look asap.

**Pull request closed without merging**
